name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            artifact_name: sky-folder-selector-windows
          - os: macos-latest
            artifact_name: sky-folder-selector-macos
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        npm install --save-dev electron@latest electron-builder@latest
        
    - name: Build
      run: |
        npm run build
        echo "Build completed"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: List build output
      run: |
        echo "Listing dist directory contents:"
        ls -la dist/
        
    - name: Check if dist directory exists
      run: |
        if [ ! -d "dist" ]; then
          echo "dist directory does not exist!"
          exit 1
        fi
        
    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/
        retention-days: 5 