name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        npm install --save-dev electron@latest electron-builder@latest
        
    - name: Build
      run: |
        npm run build
        echo "Build completed"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: List build output
      run: dir dist
        
    - name: Upload Windows artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: sky-folder-selector-windows
        path: dist/
        retention-days: 5

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        npm install --save-dev electron@latest electron-builder@latest
        
    - name: Build
      run: |
        npm run build
        echo "Build completed"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: List build output
      run: ls -la dist/
        
    - name: Upload macOS artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: sky-folder-selector-macos
        path: dist/
        retention-days: 5 